### ISSUE TITLE
Crash on break Pedistal

### ISSUE THREAD

**Issue by ghost** [denbukki/Baublelicious#8]
mayby its only on my side and mayby you already know about it. but when i break the pedistal i crash.

```
[16:09:11] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking memory connection
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:198) ~[NetworkSystem.class:?]
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118) ~[IntegratedServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752) [MinecraftServer$2.class:?]
Caused by: java.lang.NullPointerException
    at com.baublelicious.tiles.TilePedestal.onBlockBreak(TilePedestal.java:125) ~[TilePedestal.class:?]
    at com.baublelicious.blocks.BlockPedestal.breakBlock(BlockPedestal.java:76) ~[BlockPedestal.class:?]
    at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:658) ~[Chunk.class:?]
    at net.minecraft.world.World.setBlock(World.java:519) ~[World.class:?]
    at net.minecraft.world.World.setBlockToAir(World.java:651) ~[World.class:?]
    at net.minecraft.block.Block.removedByPlayer(Block.java:1670) ~[Block.class:?]
    at net.minecraft.block.Block.removedByPlayer(Block.java:1664) ~[Block.class:?]
    at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:270) ~[ItemInWorldManager.class:?]
    at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:263) ~[ItemInWorldManager.class:?]
    at net.minecraft.server.management.ItemInWorldManager.tryHarvestBlock(ItemInWorldManager.java:304) ~[ItemInWorldManager.class:?]
    at net.minecraft.server.management.ItemInWorldManager.onBlockClicked(ItemInWorldManager.java:168) ~[ItemInWorldManager.class:?]
    at net.minecraft.network.NetHandlerPlayServer.processPlayerDigging(NetHandlerPlayServer.java:523) ~[NetHandlerPlayServer.class:?]
    at net.minecraft.network.play.client.C07PacketPlayerDigging.processPacket(C07PacketPlayerDigging.java:61) ~[C07PacketPlayerDigging.class:?]
    at net.minecraft.network.play.client.C07PacketPlayerDigging.processPacket(C07PacketPlayerDigging.java:94) ~[C07PacketPlayerDigging.class:?]
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241) ~[NetworkManager.class:?]
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182) ~[NetworkSystem.class:?]
    ... 5 more
[16:09:11] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Dennis\Desktop\forge\eclipse\.\crash-reports\crash-2015-05-19_16.09.11-server.txt
[16:09:11] [Server thread/INFO]: Stopping server
[16:09:11] [Server thread/INFO]: Saving players
[16:09:11] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:displayCrashReport:388]: ---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 19-5-15 16:09
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
    at com.baublelicious.tiles.TilePedestal.onBlockBreak(TilePedestal.java:125)
    at com.baublelicious.blocks.BlockPedestal.breakBlock(BlockPedestal.java:76)
    at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:658)
    at net.minecraft.world.World.setBlock(World.java:519)
    at net.minecraft.world.World.setBlockToAir(World.java:651)
    at net.minecraft.block.Block.removedByPlayer(Block.java:1670)
    at net.minecraft.block.Block.removedByPlayer(Block.java:1664)
    at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:270)
    at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:263)
    at net.minecraft.server.management.ItemInWorldManager.tryHarvestBlock(ItemInWorldManager.java:304)
    at net.minecraft.server.management.ItemInWorldManager.onBlockClicked(ItemInWorldManager.java:168)
    at net.minecraft.network.NetHandlerPlayServer.processPlayerDigging(NetHandlerPlayServer.java:523)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.processPacket(C07PacketPlayerDigging.java:61)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.processPacket(C07PacketPlayerDigging.java:94)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at com.baublelicious.tiles.TilePedestal.onBlockBreak(TilePedestal.java:125)
    at com.baublelicious.blocks.BlockPedestal.breakBlock(BlockPedestal.java:76)
    at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:658)
    at net.minecraft.world.World.setBlock(World.java:519)
    at net.minecraft.world.World.setBlockToAir(World.java:651)
    at net.minecraft.block.Block.removedByPlayer(Block.java:1670)
    at net.minecraft.block.Block.removedByPlayer(Block.java:1664)
    at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:270)
    at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:263)
    at net.minecraft.server.management.ItemInWorldManager.tryHarvestBlock(ItemInWorldManager.java:304)
    at net.minecraft.server.management.ItemInWorldManager.onBlockClicked(ItemInWorldManager.java:168)
    at net.minecraft.network.NetHandlerPlayServer.processPlayerDigging(NetHandlerPlayServer.java:523)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.processPacket(C07PacketPlayerDigging.java:61)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.processPacket(C07PacketPlayerDigging.java:94)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@10dfc752
Stacktrace:
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)

```

**Comment by jamesbirtles** [comment]
I did not know about this.

I missed it as it only happens when there is no active bauble in there which has not happened when I've tested it.

Fix incoming
